version: '3.1'

services:
  db:
    image: postgres
    restart: always
    environment:
      - "POSTGRES_USER=docker"
      - "POSTGRES_PASSWORD=docker"
      - "POSTGRES_DB=walletstate"
    ports:
      - "5432:5432"
