### Login
POST localhost:8081/auth/login
Content-Type: application/json

{
  "username": "{{username}}",
  "password": "{{password}}"
}

### Logout
GET localhost:8081/auth/logout

### Create namespace
POST localhost:8081/api/namespaces
Content-Type: application/json

{
  "name": "test-name-2"
}

> {%
    client.global.set("namespace", response.body.id);
%}

### Get namespace
GET localhost:8081/api/namespaces/current

### Create invite
POST localhost:8081/api/namespaces/invite
Content-Type: application/json

> {%
    client.global.set("inviteCode", response.body.inviteCode);
%}

### Join namespace
POST localhost:8081/api/namespaces/join
Content-Type: application/json

{
  "inviteCode": "{{inviteCode}}"
}

### Create account
POST localhost:8081/api/accounts
Content-Type: application/json

{
  "name": "monobank white card"
}

> {%
    client.global.set("accountId", response.body.id);
%}

### Get accounts
GET localhost:8081/api/accounts

### Get account
GET localhost:8081/api/accounts/{{accountId}}

### Create category
POST localhost:8081/api/categories
Content-Type: application/json

{
  "name": "Food"
}

> {%
    client.global.set("categoryId", response.body.id);
%}

### Get categories
GET localhost:8081/api/categories

### Get category
GET localhost:8081/api/categories/{{categoryId}}

### Create record
POST localhost:8081/api/records
Content-Type: application/json

{
  "account": "{{accountId}}",
  "amount": 99.99,
  "type": "Spending",
  "category": "{{categoryId}}",
  "description": "Bananas",
  "time": "2023-06-02T14:10:20Z"
}

> {%
    client.global.set("recordId", response.body.id);
%}

### Get records
GET localhost:8081/api/records

### Get category
GET localhost:8081/api/records/{{recordId}}

